### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by lucahammer** [justinlittman/fbarc#5]
How can I find out why there was a problem with the JSON?

Full error message:
```
python fbarc.py --debug graph page altenbeken.info --levels 2 > altenbeken.jsonl
Access token expires on 2018-03-04 10:21:56+00:00
Getting graph for node altenbeken.info
Traceback (most recent call last):
  File "fbarc.py", line 476, in raise_for_fb_exception
    raise FbException(error_response)
__main__.FbException: An unknown error has occurred.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbarc.py", line 1156, in <module>
    main()
  File "fbarc.py", line 214, in main
    args.csv_output_dir, fb)
  File "fbarc.py", line 273, in graph_command
    exclude_definition_names=exclude_definition_name), graph_outputs)
  File "fbarc.py", line 298, in print_graphs
    for graph in graph_iter:
  File "fbarc.py", line 522, in get_nodes
    for node_graph in self._get_nodes(node_counter, node_queue, queued_nodes, le
vels, exclude_definition_names):
  File "fbarc.py", line 536, in _get_nodes
    node_graph_dict = self.get_node_batch(node_ids, definition_name)
  File "fbarc.py", line 617, in get_node_batch
    nodes_graph_dict = self._perform_http_post(url, data=params)
  File "fbarc.py", line 908, in _perform_http_post
    raise_for_fb_exception(response, data=data)
  File "fbarc.py", line 477, in raise_for_fb_exception
    except json.decoder.JSONDecodeError:
AttributeError: 'module' object has no attribute 'JSONDecodeError'

```
 
debug.log
```
2018-01-05 12:05:15,428 ERROR Error for https://graph.facebook.com/v2.11 ({'fields': 'id,metadata{type},description,end_time,event_times,name,start_time,attending_count,category,cover,declined_count,interested_count,is_canceled,maybe_count,noreply_count,owner,picture,place,timezone,type,updated_time,comments.limit(2000){id,created_time,from,message,permalink_url},feed.limit(25){id,created_time,from,message,permalink_url,status_type,to,updated_time},live_videos.limit(100){id,creation_time,description,permalink_url,title},photos.limit(100){id,created_time,link,name,updated_time}', 'access_token': 'XXXXXX', 'ids': '330364757445239,1785087901790238,1778205972478904,1348214928621073,215387655660218,268732113631738,396768557350139,1633347510043387,1027045984065537,139391659967274,1523274661042677,1832586256990227,985206564948474,300970570319747,193476294470573,238752436577395,1178518992264453,580038218861570,180063365812330,237478843337911', 'method': 'GET', 'metadata': 1}): {
    "error": {
        "message": "An unknown error has occurred.",
        "code": 1,
        "fbtrace_id": "A98KjDQxfoZ",
        "type": "OAuthException"
    }
}
```

**Comment by lucahammer** [comment]
Haven't solved it yet, but omitting events in the local definition works around it.

**Comment by justinlittman** [comment]
Working on a new approach for handling these sorts of intermittent errors.

**Comment by justinlittman** [comment]
@lucahammer Give it a try again with the latest from master.

**Comment by lucahammer** [comment]
On a small page where I got an error before, it works now. But with bigger pages I still get an error. 

`python fbarc.py graph page Volkspartei --levels 5 > oevp.jsonl`

```
Access token expires on 2018-03-07 17:06:46+00:00
Getting graph for node Volkspartei

Traceback (most recent call last):
  File "fbarc.py", line 452, in raise_for_fb_exception
    raise FbException(error_response)
__main__.FbException: An unknown error has occurred.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbarc.py", line 1152, in <module>
    main()
  File "fbarc.py", line 213, in main
    args.csv_output_dir, fb)
  File "fbarc.py", line 255, in graph_command
    exclude_definition_names=exclude_definition_name), graph_outputs)
  File "fbarc.py", line 280, in print_graphs
    for graph in graph_iter:
  File "fbarc.py", line 496, in get_nodes
    for node_graph in self._get_nodes(node_counter, node_queue, queued_nodes, le
vels, exclude_definition_names):
  File "fbarc.py", line 510, in _get_nodes
    node_graph_dict = self.get_node_batch(node_ids, definition_name)
  File "fbarc.py", line 600, in get_node_batch
    nodes_graph_dict = self._perform_http_post(url, data=params)
  File "fbarc.py", line 895, in _perform_http_post
    raise_for_fb_exception(response, data=data)
  File "fbarc.py", line 453, in raise_for_fb_exception
    except json.decoder.JSONDecodeError:
AttributeError: 'module' object has no attribute 'JSONDecodeError'

```

log:
```
2018-01-08 15:57:45,791 ERROR Error for https://graph.facebook.com/v2.11 ({'ids': '503908863292867,181156159083846', 'metadata': 1, 'method': 'GET', 'fields': 'id,metadata{type},description,end_time,event_times,name,start_time,attending_count,category,cover,declined_count,interested_count,is_canceled,maybe_count,noreply_count,owner,picture,place,timezone,type,updated_time,comments.limit(2000){id,created_time,message,permalink_url},feed.limit(25){id,created_time,from,message,permalink_url,status_type,to,updated_time},live_videos.limit(100){id,creation_time,description,permalink_url,title},photos.limit(100){id,created_time,link,name,updated_time}', 'access_token': 'XXX'}): {
    "error": {
        "code": 1,
        "type": "OAuthException",
        "message": "An unknown error has occurred.",
        "fbtrace_id": "CGO3oFZnUDA"
    }
}
```

Is that the Facebook-API acting up?

**Comment by justinlittman** [comment]
API acting up no more than normal. I'm in the process of fine-tuning the error handling. Try again with the latest from master -- Volkspartei worked for me.

**Comment by justinlittman** [comment]
Also, remove any local definitions you may have.

**Comment by justinlittman** [comment]
@lucahammer Can you still reproduce this (with the latest code and local defs removed)?

**Comment by lucahammer** [comment]
Sorry for the late response. I removed fbarc completely and restarted from source. But I still get an error. 

```
 python fbarc.py graph page Volkspartei --levels 5
> oevp.jsonl
Access token expires on 2018-03-23 13:12:15+00:00
Getting graph for node Volkspartei
Traceback (most recent call last):
  File "fbarc.py", line 432, in raise_for_fb_exception
    raise FbException(error_response)
__main__.FbException: An unknown error has occurred.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbarc.py", line 1132, in <module>
    main()
  File "fbarc.py", line 213, in main
    args.csv_output_dir, fb)
  File "fbarc.py", line 255, in graph_command
    exclude_definition_names=exclude_definition_name), graph_outputs)
  File "fbarc.py", line 260, in print_graphs
    for graph in graph_iter:
  File "fbarc.py", line 476, in get_nodes
    for node_graph in self._get_nodes(node_counter, node_queue, queued_nodes, levels, exclude_definition_names):
  File "fbarc.py", line 490, in _get_nodes
    node_graph_dict = self.get_node_batch(node_ids, definition_name)
  File "fbarc.py", line 580, in get_node_batch
    nodes_graph_dict = self._perform_http_post(url, data=params)
  File "fbarc.py", line 875, in _perform_http_post
    raise_for_fb_exception(response, data=data)
  File "fbarc.py", line 433, in raise_for_fb_exception
    except json.decoder.JSONDecodeError:
AttributeError: 'module' object has no attribute 'JSONDecodeError'

```

**Comment by lucahammer** [comment]
I spun up an Ubuntu VM and tried it there. Worked without an issue. I still don't know why I get the error on Raspbian, but assume it's something on my side.

**Comment by justinlittman** [comment]
Suffice to say I've never tried it on Raspbian. Thanks for the bug report and let me know if you have ideas / uses for fbarc.
