### ISSUE TITLE
could not build url for endpoint node 

### ISSUE THREAD

**Issue by webcoderz** [justinlittman/fbarc#6]
python3 fbarc.py graph page MarkRWarner | python fbarc_viewer.py
Warning: Using an app token. You may encounter authorization problems.
Getting graph for node MarkRWarner

Traceback (most recent call last):
  File "fbarc.py", line 875, in _perform_http_post
    raise_for_fb_exception(response, data=data)
  File "fbarc.py", line 432, in raise_for_fb_exception
    raise FbException(error_response)
__main__.FbException: Unsupported get request. Object with ID 'MarkRWarner' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbarc.py", line 875, in _perform_http_post
    raise_for_fb_exception(response, data=data)
  File "fbarc.py", line 432, in raise_for_fb_exception
    raise FbException(error_response)
__main__.FbException: Unsupported get request. Object with ID 'MarkRWarner' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbarc.py", line 875, in _perform_http_post
    raise_for_fb_exception(response, data=data)
  File "fbarc.py", line 432, in raise_for_fb_exception
    raise FbException(error_response)
__main__.FbException: Unsupported get request. Object with ID 'MarkRWarner' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbarc.py", line 875, in _perform_http_post
    raise_for_fb_exception(response, data=data)
  File "fbarc.py", line 432, in raise_for_fb_exception
    raise FbException(error_response)
__main__.FbException: Unsupported get request. Object with ID 'MarkRWarner' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbarc.py", line 875, in _perform_http_post
    raise_for_fb_exception(response, data=data)
  File "fbarc.py", line 432, in raise_for_fb_exception
    raise FbException(error_response)
__main__.FbException: Unsupported get request. Object with ID 'MarkRWarner' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbarc.py", line 875, in _perform_http_post
    raise_for_fb_exception(response, data=data)
  File "fbarc.py", line 432, in raise_for_fb_exception
    raise FbException(error_response)
__main__.FbException: Unsupported get request. Object with ID 'MarkRWarner' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbarc.py", line 875, in _perform_http_post
    raise_for_fb_exception(response, data=data)
  File "fbarc.py", line 432, in raise_for_fb_exception
    raise FbException(error_response)
__main__.FbException: Unsupported get request. Object with ID 'MarkRWarner' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbarc.py", line 875, in _perform_http_post
    raise_for_fb_exception(response, data=data)
  File "fbarc.py", line 432, in raise_for_fb_exception
    raise FbException(error_response)
__main__.FbException: Unsupported get request. Object with ID 'MarkRWarner' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbarc.py", line 875, in _perform_http_post
    raise_for_fb_exception(response, data=data)
  File "fbarc.py", line 432, in raise_for_fb_exception
    raise FbException(error_response)
__main__.FbException: Unsupported get request. Object with ID 'MarkRWarner' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbarc.py", line 488, in _get_nodes
    node_graph_dict[node_ids[0]] = self.get_node(node_ids[0], definition_name)
  File "fbarc.py", line 567, in get_node
    raise e
  File "fbarc.py", line 546, in get_node
    node_graph = self._perform_http_post(url, data=params)
  File "fbarc.py", line 914, in _perform_http_post
    **kwargs)
  File "fbarc.py", line 914, in _perform_http_post
    **kwargs)
  File "fbarc.py", line 914, in _perform_http_post
    **kwargs)
  [Previous line repeated 5 more times]
  File "fbarc.py", line 910, in _perform_http_post
    raise e
  File "fbarc.py", line 875, in _perform_http_post
    raise_for_fb_exception(response, data=data)
  File "fbarc.py", line 432, in raise_for_fb_exception
    raise FbException(error_response)
__main__.FbException: Unsupported get request. Object with ID 'MarkRWarner' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbarc.py", line 1132, in <module>
    main()
  File "fbarc.py", line 213, in main
    args.csv_output_dir, fb)
  File "fbarc.py", line 255, in graph_command
    exclude_definition_names=exclude_definition_name), graph_outputs)
  File "fbarc.py", line 260, in print_graphs
    for graph in graph_iter:
  File "fbarc.py", line 476, in get_nodes
    for node_graph in self._get_nodes(node_counter, node_queue, queued_nodes, levels, exclude_definition_names):
  File "fbarc.py", line 512, in _get_nodes
    log.warning('Skipping %s due to unexpected GraphMethodException: %s', node_id, e)
UnboundLocalError: local variable 'node_id' referenced before assignment
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2018-01-14 16:56:01,616] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "fbarc_viewer.py", line 32, in home
    return redirect(url_for('node', node_id=first_node_id))
  File "/usr/lib/python2.7/dist-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'node'. Did you forget to specify values ['node_id']?
127.0.0.1 - - [14/Jan/2018 16:56:01] "GET / HTTP/1.1" 500 -

**Comment by justinlittman** [comment]
Thanks @akrolla -- I'll check it out.

In the meantime, I'd suggest [getting a user access token](https://github.com/justinlittman/fbarc#tokens) and trying again.

**Comment by webcoderz** [comment]
thanks :) i was wondering how to do that,
